import React, { useEffect, useState } from "react";
import { API_BASE } from "./dashboardConstants";

// ── AI Advisory Panel ────────────────────────────────────────
// Calls GET /api/zones/ai-advisory → displays Gemini-generated conservation text.
export default function AIAdvisoryPanel({ onClose }) {
  const [advisory, setAdvisory] = useState("");
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  useEffect(() => {
    const fetchAdvisory = async () => {
      try {
        const token = localStorage.getItem("token");
        const res = await fetch(`${API_BASE}/api/zones/ai-advisory`, {
          headers: { Authorization: `Bearer ${token}` },
        });
        const ct = res.headers.get("content-type") || "";
        if (!ct.includes("application/json")) {
          throw new Error("Server unreachable");
        }
        const data = await res.json();
        if (!res.ok) {
          throw new Error(data.message || "Failed to fetch advisory");
        }
        setAdvisory(data.advisory);
      } catch (err) {
        setError(err.message);
      } finally {
        setLoading(false);
      }
    };

    fetchAdvisory();
  }, []);

  return (
    <div
      style={{
        position: "fixed",
        inset: 0,
        background: "rgba(10,22,40,0.6)",
        zIndex: 1000,
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
      }}
      onClick={(e) => e.target === e.currentTarget && onClose()}
    >
      <div
        style={{
          background: "#fff",
          borderRadius: "14px",
          width: "100%",
          maxWidth: "560px",
          padding: "30px",
          boxShadow: "0 24px 60px rgba(0,0,0,0.2)",
        }}
      >
        {/* Header */}
        <div
          style={{
            display: "flex",
            justifyContent: "space-between",
            alignItems: "flex-start",
            marginBottom: "18px",
          }}
        >
          <div>
            <div
              style={{
                display: "flex",
                alignItems: "center",
                gap: "8px",
                marginBottom: "4px",
              }}
            >
              <span style={{ fontSize: "20px" }}>✨</span>
              <h2
                style={{
                  margin: 0,
                  fontSize: "17px",
                  fontWeight: "700",
                  color: "#0a1628",
                }}
              >
                AI Conservation Advisory
              </h2>
            </div>
            <p style={{ margin: 0, fontSize: "12px", color: "#8a96b0" }}>
              Generated by Gemini AI based on your active restricted zones
            </p>
          </div>
          <button
            onClick={onClose}
            style={{
              background: "transparent",
              border: "none",
              fontSize: "18px",
              cursor: "pointer",
              color: "#8a96b0",
            }}
          >
            ✕
          </button>
        </div>

        {/* Content */}
        {loading ? (
          <div style={{ textAlign: "center", padding: "30px 0" }}>
            <div style={{ fontSize: "28px", marginBottom: "10px" }}>⏳</div>
            <p style={{ color: "#8a96b0", fontSize: "13px" }}>
              Generating advisory from Gemini AI…
            </p>
          </div>
        ) : error ? (
          <p style={{ color: "#e53e3e", fontSize: "13px" }}>{error}</p>
        ) : (
          <div
            style={{
              background: "linear-gradient(135deg, #f0f7ff 0%, #f5f0ff 100%)",
              border: "1px solid #dde3ee",
              borderRadius: "10px",
              padding: "20px 22px",
            }}
          >
            {advisory
              .split("\n")
              .filter(Boolean)
              .map((line, i) => (
                <p
                  key={i}
                  style={{
                    margin: "0 0 8px",
                    fontSize: "13px",
                    color: "#2d3a55",
                    lineHeight: "1.7",
                  }}
                >
                  {line}
                </p>
              ))}
          </div>
        )}

        <button
          onClick={onClose}
          style={{
            marginTop: "20px",
            width: "100%",
            padding: "10px",
            background: "#f3f5f8",
            border: "1px solid #dde3ee",
            borderRadius: "8px",
            fontSize: "13px",
            color: "#3a4565",
            cursor: "pointer",
            fontWeight: "500",
          }}
        >
          Close
        </button>
      </div>
    </div>
  );
}
